### ISSUE TITLE
第三章:项目管理过程组

### ISSUE THREAD

**Issue by YasuoSkywalker** [Hikawasser/Software-Project-Management-Notes#2]
第三章：项目管理过程组 中的
3.1 项目管理过程组 的二级标题 “首尾过程” 应为 “收尾过程”

**Comment by Hikawasser** [comment]
已修改，谢谢~
![image](https://github.com/Hikawasser/Software-Project-Management-Notes/assets/98450248/6ad0c646-bcc5-42aa-a0a5-e39a4b1beeac)
